
server:
  port: 9092

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:~/testdb1
    username: sa
    password:
  application:
    name: PAYMENT-SERVICE
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://35.154.173.22:8761/eureka}