server:
  port: 8086

spring:
  application:
    name: PAYMENT-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    username: root
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform:
      org.hibernate.dialect.MySQL8Dialect




